"use client";

import Link from "next/link";

const T = {
  green: "#10b981", bg: "#050b18", surface: "#0a1628",
  border: "#1e293b", text: "#f1f5f9", muted: "#64748b",
};

const SECTIONS = [
  { title: "1. Service Description", content: "Proofpoint provides AI-powered Customer Success tools including ROI report generation, industry benchmarking, next action intelligence, and email drafting. Reports are generated using AI and should be reviewed for accuracy before distribution." },
  { title: "2. Account Terms", content: "You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. One person or entity may not maintain more than one free trial." },
  { title: "3. Acceptable Use", content: "You agree to use Proofpoint only for lawful business purposes. You may not use the service to generate misleading ROI claims, falsify benchmark data, or misrepresent business metrics to customers or stakeholders." },
  { title: "4. Subscription & Billing", content: "Starter plan: $39/seat/month. Growth plan: $79/seat/month. Scale plan: $119/seat/month. Annual billing available at 15% discount. All plans include a 30-day free trial with full Scale-tier access. You may cancel at any time. Refunds are not provided for partial billing periods." },
  { title: "5. Data Ownership", content: "You retain ownership of all data you input into Proofpoint. We do not share your data with third parties except as necessary to provide the service (e.g., AI processing, email delivery)." },
  { title: "6. AI-Generated Content", content: "Reports and recommendations generated by Proofpoint's AI are provided as business tools, not financial or legal advice. You are responsible for reviewing and verifying all AI-generated content before use." },
  { title: "7. Limitation of Liability", content: "Proofpoint is provided 'as is' without warranties. We are not liable for business decisions made based on AI-generated reports. Our total liability shall not exceed the amount you paid in the preceding 12 months." },
  { title: "8. Termination", content: "Either party may terminate at any time. Upon termination, your data will be available for export for 30 days, after which it may be permanently deleted." },
];

export default function TermsPage() {
  return (
    <div style={{ background: T.bg, color: T.text, fontFamily: "'DM Sans', sans-serif", minHeight: "100vh" }}>
      <nav style={{ padding: "16px 40px", borderBottom: `1px solid ${T.border}44`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Link href="/" style={{ textDecoration: "none", fontFamily: "'Playfair Display', serif", fontSize: 22, color: T.text }}>Proof<span style={{ color: T.green }}>point</span></Link>
        <Link href="/" style={{ fontSize: 13.5, color: T.muted, textDecoration: "none" }}>← Back to Home</Link>
      </nav>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "50px 20px" }}>
        <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 32, fontWeight: 700, color: T.text, marginBottom: 8 }}>Terms & Conditions</h1>
        <p style={{ fontSize: 13, color: T.muted, marginBottom: 32 }}>Last updated: March 1, 2026</p>
        {SECTIONS.map(s => (
          <div key={s.title} style={{ marginBottom: 24 }}>
            <h3 style={{ fontSize: 15, fontWeight: 600, color: T.text, marginBottom: 8 }}>{s.title}</h3>
            <p style={{ fontSize: 13.5, color: T.muted, lineHeight: 1.8 }}>{s.content}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
